def is_debug() -> bool: ...
def tea16_encrypt(text: bytes, key: bytes) -> bytes: ...
def tea16_decrypt(text: bytes, key: bytes) -> bytes: ...
def qqtea_encrypt(text: bytes, key: bytes) -> bytes: ...
def qqtea_decrypt(text: bytes, key: bytes) -> bytes: ...
