def xor(a: bytes, b: bytes) -> bytes: ...
def pytea16_encrypt(plain: bytes, key: bytes) -> bytes: ...
def pytea16_decrypt(cipher: bytes, key: bytes) -> bytes: ...
def pyqqtea_encrypt(plain: bytes, key: bytes) -> bytes: ...
def pyqqtea_decrypt(v: bytes, secret_key: bytes) -> bytes: ...
